server:
  port: 8866
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hudoufu/blog.git
          search-paths: config-repo